version: "3.7"

services:
  database:
    image: postgres
    container_name: database_broadcasts
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=broadcasts
    volumes:
      - pgdata:/data/postgres

  app:
    build:
      context: ./
      dockerfile: dockerfile.dev
    container_name: broadcasts_api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local